name: Download ReHLDS and Reunion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download latest ReHLDS release
        run: |
          curl -L -o rehlds.zip $(curl -s https://api.github.com/repos/dreamstalker/rehlds/releases/latest | grep "rehlts" | cut -d '"' -f 4)

      - name: Download latest Reunion release
        run: |
          curl -L -o reunion.zip $(curl -s https://api.github.com/repos/Reunion/REUNION/releases/latest | grep "Reunion" | cut -d '"' -f 4)

      - name: Unzip files
        run: |
          mkdir combined
          unzip rehlds.zip -d rehlds
          unzip reunion.zip -d reunion
          cp -r rehlds/* combined/
          cp -r reunion/* combined/

      - name: Upload combined folder as artifact
        uses: actions/upload-artifact@v2
        with:
          name: combined-rehlds-reunion
          path: combined/
