name: create-platform-cs16

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Download reHLDS repo
              uses: robinraju/release-downloader@v1
              with: 
                repository: dreamstalker/rehlds
                latest: true