name: Download rehlds Release

on:
  workflow_dispatch:

jobs:
  download-rehlds-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download release from dreamstalker/rehlds
      run: |
        mkdir -p downloaded_releases/rehlds
        curl -L -o downloaded_releases/rehlds/rehlds_latest.zip \
        https://github.com/dreamstalker/rehlds/releases/download/3.13.0.788/rehlds-bin-3.13.0.788.zip
    - name: Commit and push the downloaded release
      run: |
        git config --local user.name "Marti Dimitrov"
        git config --local user.email "marti.dimitrov1@icloud.com"
        git add downloaded_releases
        git commit -m "Downloaded latest rehlds release"
        git push
