name: create-platform-cs16

on: push
permissions:
  contents: write

env: 
  folder_rehlds: rehlds-bin

jobs:
    build-rehlds:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
             
            - name: Delete old reHLDS files
              run: rm -rf ${{ env.folder_rehlds }}
            
            - name: Download reHLDS release files
              uses: robinraju/release-downloader@v1
              with: 
                repository: dreamstalker/rehlds
                latest: true
                fileName: "${{ env.folder_rehlds }}-*"
                out-file-path: ${{ env.folder_rehlds }}
                extract: true
            
            - name: Delete the zip file from the download of reHLDS
              run: |
                rm -rf ${{ env.folder_rehlds }}/rehlds-bin-*.zip
                ls -la

            - name: Push reHLDS files to repo
              run: |
                git config --local user.email ${{ vars.USER_EMAIL }}
                git config --local user.name ${{ vars.USER_NAME }}
                git add /home/runner/work/cs16/cs16/${{ env.folder_rehlds }}
                git commit -m "rehlds"
                git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ vars.USER_NAME }}/cs16.git