name: create-platform-cs16-rehlds

on: push
permissions:
  contents: write

env: 
  folder_rehlds: rehlds-bin
  repository: dreamstalker/rehlds

jobs:
    build-rehlds:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Download reHLDS release files
              uses: robinraju/release-downloader@v1
              with: 
                repository: ${{ env.repository }}
                latest: true
                fileName: "${{ env.folder_rehlds }}-*"
                out-file-path: ${{ env.folder_rehlds }}
                extract: true
            
            - name: Delete unneeded files (zip, hlsdk)
              run: |
                rm -rf ${{ env.folder_rehlds }}/rehlds-bin-*.zip
                rm -rf ${{ env.folder_rehlds }}/hlsdk

            - name: Push reHLDS files to repo
              run: |
                git config --local user.email ${{ vars.USER_EMAIL }}
                git config --local user.name ${{ vars.USER_NAME }}
                git add /home/runner/work/cs16/cs16/${{ env.folder_rehlds }}
                git commit -m "rehlds"
                git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ vars.USER_NAME }}/cs16.git