name: Download ReHLDS

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Clone ReHLDS Repository
        run: |
          git clone https://github.com/dreamstalker/rehlds.git
          # Optional: Check out a specific branch if necessary
          cd rehlds
          # git checkout <branch> # Uncomment and replace <branch> if needed

      - name: List files in the ReHLDS repository
        run: |
          ls -la rehlds
