name: Create Platform for CS 1.6 Server

on:
  push:
    branches:
      - main  
  workflow_dispatch:  # Allow manual triggering
jobs:
  create-platform:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  

      - name: Download ReHLDS
        run: |
          echo "Downloading ReHLDS..."
          wget -q https://github.com/dreamstalker/rehlds/archive/refs/tags/v5.0.0.tar.gz -O rehlds.tar.gz
          mkdir rehlds
          tar -xzf rehlds.tar.gz -C rehlds --strip-components=1

      - name: Download ReUnion
        run: |
          echo "Downloading ReUnion..."
          wget -q https://github.com/reunion-team/reunion/archive/refs/tags/v0.1.0.tar.gz -O reunion.tar.gz
          mkdir reunion
          tar -xzf reunion.tar.gz -C reunion --strip-components=1

      - name: List downloaded files
        run: |
          echo "ReHLDS files:"
          ls -l rehlds
          echo "ReUnion files:"
          ls -l reunion
