name: create-platform-cs16

on: push

jobs:
    build-rehlds:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Download reHLDS repo
              uses: robinraju/release-downloader@v1
              with: 
                repository: dreamstalker/rehlds
                latest: true
                zipBall: true
                extract: true
                out-file-path: rehlds

            - name: 
              run: |
                ls -la rehlds && 
                ls -la dreamstalker-rehlds-*