name: Combine ReHLDS and ReUnion Files

on:
  push:
    branches:
      - main  # Change to your default branch if needed
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  combine_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Combined Directory
        run: mkdir -p combined

      - name: Download ReHLDS Files
        run: |
          curl -L -o combined/rehl_files.zip https://example.com/path/to/rehlds/files.zip
          # Unzip the downloaded files if needed
          unzip combined/rehl_files.zip -d combined/

      - name: Download ReUnion Files
        run: |
          curl -L -o combined/reunion_files.zip https://example.com/path/to/reunion/files.zip
          # Unzip the downloaded files if needed
          unzip combined/reunion_files.zip -d combined/

      - name: List Combined Directory
        run: ls -la combined

      - name: Commit and Push Changes
        run: |
          git config --local user.email "marti.dimitrov1@icloud.com"
          git config --local user.name "Marti Dimitrov"
          git add combined/
          git commit -m "Combined ReHLDS and ReUnion files"
          git push
