name: Build ReHLDS and Reunion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step to download ReHLDS
      - name: Download ReHLDS
        run: |
          wget -qO- https://github.com/dreamstalker/rehlds/releases/download/<version>/rehlds-bin.zip -O rehlds-bin.zip
          unzip rehlds-bin.zip -d rehlds
          rm rehlds-bin.zip

      # Step to download Reunion
      - name: Download Reunion
        run: |
          wget -qO- https://github.com/dreamstalker/reunion/releases/download/<version>/reunion-bin.zip -O reunion-bin.zip
          unzip reunion-bin.zip -d reunion
          rm reunion-bin.zip
