name: create-platform-cs16

on: push

jobs:
    build-rehlds:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Download reHLDS repo
              uses: robinraju/release-downloader@v1
              with: 
                repository: dreamstalker/rehlds
                zipBall: true
                extract: true
                fileName: "rehlds-bin-*"
                out-file-path: "rehlds-bin"

            - name: Push reHLDS files to repo
              run: |
                git config --local user.email "marti.dimitrov1@icloud.com"
                git config --local user.name "Marti Dimitrov"
                git add .
                git commit -m "rehlds"
                git push origin main      