name: create-platform-cs16-rehlds

on: push
permissions:
  contents: write

env: 
  folder_rehlds: rehlds-bin
  repository_rehlds: dreamstalker/rehlds
  folder_regamedll: regamedll
  repository_regamedll: s1lentq/ReGameDLL_CS


jobs:
    build-rehlds:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Download reHLDS release files
              uses: robinraju/release-downloader@v1
              with: 
                repository: ${{ env.repository_rehlds }}
                latest: true
                fileName: "${{ env.folder_rehlds }}-*"
                out-file-path: ${{ env.folder_rehlds }}
                extract: true

            - name: Download reGameDLL_CS release files
              uses: robinraju/release-downloader@v1
              with: 
                repository: ${{ env.repository_regamedll}}
                latest: true
                fileName: "${{ env.folder_regamedll }}-*"
                out-file-path: ${{ env.folder_regamedll }}
                extract: true

            - name: Delete unneeded files (zip, hlsdk, win32)
              run: |
                rm -rf ${{ env.folder_rehlds }}/rehlds-bin-*.zip
                rm -rf ${{ env.folder_rehlds }}/hlsdk
                rm -rf ${{ env.folder_rehlds }}/bin/win32
            
            - name: Delete unneeded files (zip, hlsdk, win32)
              run: |
                rm -rf ${{ env.folder_regamedll }}/regamedll-bin-*.zip
                rm -rf ${{ env.folder_regamedll }}/cssdk
                rm -rf ${{ env.folder_regamedll }}/bin/win32


            - name: Push new files to repo
              run: |
                git config --local user.email ${{ vars.USER_EMAIL }}
                git config --local user.name ${{ vars.USER_NAME }}
                git add ./${{ env.folder_rehlds }} ./${{ env.folder_regamedll }}
                git commit -m "platform"
                git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ vars.USER_NAME }}/cs16.git