name: Build ReHLDS and Reunion

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step to download the latest ReHLDS
      - name: Download latest ReHLDS
        run: |
          # Download and unzip
          wget -qO- https://github.com/dreamstalker/rehlds/archive/refs/tags/3.13.0.788.zip -O rehlds-bin.zip
          unzip rehlds-bin.zip -d rehlds
          rm rehlds-bin.zip
