name: Download Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download_and_extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download ReHLDS Release
        run: |
          curl -L -o rehlds.zip https://github.com/dreamstalker/rehlds/releases/latest/download/rehlds.zip
          mkdir -p rehlds && unzip rehlds.zip -d rehlds

      - name: Download ReUnion Release
        run: |
          curl -L -o reunion.zip https://github.com/reunion/reunion/releases/latest/download/reunion.zip
          mkdir -p reunion && unzip reunion.zip -d reunion
