name: download-platform-cs16

on: push
permissions:
  contents: write

env: 
  repository_rehlds: dreamstalker/rehlds
  repository_regamedll: s1lentq/ReGameDLL_CS
  repository_metamod_r: rehlds/metamod-r
  repository_reapi: rehlds/reapi
  repository_reunion: rehlds/reunion
  download_url_amxmodx_base: https://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-base-linux.tar.gz
  download_url_amxmodx_cstrike: http://www.amxmodx.org/amxxdrop/1.10/amxmodx-latest-cstrike-linux.tar.gz

  folder_rehlds: rehlds
  folder_regamedll: regamedll
  folder_metamod_r: metamod
  folder_reapi: reapi
  folder_reunion: reunion
  folder_amxmodx_base: amxmodx_base
  folder_amxmodx_cstrike: amxmodx_cstrike
  folder_amxmodx: amxmodx

jobs:
    build-rehlds:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Download reHLDS
              uses: robinraju/release-downloader@v1
              with: 
                repository: ${{ env.repository_rehlds }}
                latest: true
                fileName: "${{ env.folder_rehlds }}-bin-*"
                out-file-path: ${{ env.folder_rehlds }}
                extract: true

            - name: Download reGameDLL
              uses: robinraju/release-downloader@v1
              with: 
                repository: ${{ env.repository_regamedll }}
                latest: true
                fileName: "${{ env.folder_regamedll }}-*"
                out-file-path: ${{ env.folder_regamedll }}
                extract: true
            
            - name: Download metamod-r
              uses: robinraju/release-downloader@v1
              with: 
                repository: ${{ env.repository_metamod_r }}
                latest: true
                fileName: "${{ env.folder_metamod_r }}-*"
                out-file-path: ${{ env.folder_metamod_r }}
                extract: true
  
            - name: Download reapi
              uses: robinraju/release-downloader@v1
              with: 
                repository: ${{ env.repository_reapi }}
                latest: true
                fileName: "${{ env.folder_reapi }}-*"
                out-file-path: ${{ env.folder_reapi }}
                extract: true

            - name: Download reunion
              uses: robinraju/release-downloader@v1
              with: 
                repository: ${{ env.repository_reunion }}
                latest: true
                fileName: "${{ env.folder_reunion}}-*"
                out-file-path: ${{ env.folder_reunion}}
                extract: true

            - name: Download amxmodx_base && amxmodx_cstrike
              run: |
                curl -L -o ${{ env.folder_amxmodx_base }}.tar.gz ${{ env.download_url_amxmodx_base }} &&
                curl -L -o ${{ env.folder_amxmodx_cstrike }}.tar.gz ${{ env.download_url_amxmodx_cstrike }}

            - name: Extract the amxmodx_base tar.gz file
              run: |
                mkdir -p ${{ env.folder_amxmodx }} &&
                tar -xzf ${{ env.folder_amxmodx_base }}.tar.gz -C ${{ env.folder_amxmodx }} &&
                tar -xzf ${{ env.folder_amxmodx_cstrike }}.tar.gz -C ${{ env.folder_amxmodx }} 

            - name: Delete unneeded files (zip, hlsdk, win32, )
              run: |
                rm -rf ${{ env.folder_rehlds }}/rehlds-bin-*.zip
                rm -rf ${{ env.folder_rehlds }}/hlsdk
                rm -rf ${{ env.folder_rehlds }}/bin/win32
            
            - name: Delete unneeded files (zip, cssdk, win32)
              run: |
                rm -rf ${{ env.folder_regamedll }}/regamedll-bin-*.zip
                rm -rf ${{ env.folder_regamedll }}/cssdk
                rm -rf ${{ env.folder_regamedll }}/bin/win32

            - name: Delete unneeded files (zip, sdk, example_plugin)
              run: |
                rm -rf ${{ env.folder_metamod_r }}/metamod-bin-*.zip
                rm -rf ${{ env.folder_metamod_r }}/sdk
                rm -rf ${{ env.folder_metamod_r }}/example_plugin

            - name: Delete unneeded files (zip)
              run: |
                rm -rf ${{ env.folder_reapi }}/reapi-bin-*.zip

            - name: Delete unneeded files (zip)
              run: |
                rm -rf ${{ env.folder_reunion }}/reunion-*.zip

            - name: Delete base tar.gz
              run: |
                rm -rf ${{ env.folder_amxmodx_base }}.tar.gz

            - name: Delete cstrike tar.gz
              run: |
                rm -rf ${{ env.folder_amxmodx_cstrike }}.tar.gz

            - name: Push new files to repo
              run: |
                git config --local user.email ${{ vars.USER_EMAIL }}
                git config --local user.name ${{ vars.USER_NAME }}
                git add \
                ./${{ env.folder_rehlds }} \
                ./${{ env.folder_regamedll }} \
                ./${{ env.folder_metamod_r }} \
                ./${{ env.folder_reapi }} \
                ./${{ env.folder_reunion }} \
                ./${{ env.folder_amxmodx_base }} \
                ./${{ env.folder_amxmodx_cstrike }}
                git commit -m "platform"
                git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ vars.USER_NAME }}/cs16.git